name: scan workflow

on: push

jobs:
    meterian_scan:
        name: Meterian client scan
        runs-on: ubuntu-latest
        steps: 
          - name: Checkout
            uses: actions/checkout@v2
          - name: Scan project with the Meterian client
            uses: MeterianHQ/meterian-github-action@autofix-prs-and-issues
            env:
              GITHUB_TOKEN: ${{ github.token }}
              CLIENT_CANARY_FLAG: "--canary"
            with:
                oss: true
                autofix: conservative+vulns,safe+all
                autofix_issue_branches: "master"
                cli_args: --report-console:licensing

