name: scan workflow

on: push

jobs:
    meterian_scan:
        name: Meterian client scan
        runs-on: ubuntu-latest
        steps: 
          - name: Checkout
            uses: actions/checkout@v2
          - name: Scan project with the Meterian client
            uses: MeterianHQ/meterian-github-action@v1.0.9
            env:
              GITHUB_TOKEN: ${{ github.token }}
            with:
                oss: true
                autofix_security: conservative
                autofix_stability: safe
                autofix_with_report: true
                cli_args: --report-console:licensing --debug

